language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    
# before_install:
#   - chmod +x ./meetme/mvnw
#   - cd meetme
  
script: "mvn clean package"

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2
    - $HOME/.mvn

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - wpdlxldpf4@gmail.com
