language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    
# build 파일 path & auth
before_install:
  - chmod +x ./meetme/mvnw
  - cd meetme

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
script: "mvn clean package"

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2
    - $HOME/.mvn

#s3 deploy setting
before_deploy:
  - cd ../
  - zip -r yedam-springboot-webservice meetme
  - cd meetme
  - mkdir -p deploy
  - mv yedam-springboot-webservice.zip deploy/yedam-springboot-webservice.zip

  
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yedam-spring.boot-webservice
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yedam-spring.boot-webservice
    key: yedam-springboot-webservice.zip
    bundle_type: zip
    appication: yedam-springboot-webservice
    deployment_group: yedam-springboot-webservice
    region: ap-northeast-2
    wait-until-deployed: true
